In [1]:
import os
if os.getcwd().endswith('scripts'):
    os.chdir('..')
print(f"Current working directory: {os.getcwd()}")

Current working directory: /data6/yuzihan/WorkSpace/35-HuaweiCrowdSimulation/HuaweiCrowdSimulationCode

In [2]:
from src.dataset import ETHDataset, UCYDataset, SDDDataset, GCDataset, WayMoDataset
from argparse import Namespace
from src.utils.logger import init_logger

init_logger('src')

args = Namespace(
    name="train",
    exp_name="20251009_train_122049_LM2",
    device="cuda:0",
    batch_size=256,
    lr=0.001,
    epochs=10000,
    patience=20,
    sampling_method="DDIM",
    T=100,
    sample_num=1,
    denoise_step=5,
    hist_step=8,
    pred_step=1,
    skip_step=1,
    roll_step=12,
    fps=2.5,
    dot_per_meter=5,
    seed=550,
    save_dir="./logs/train",
    debug=False,
    model_dim=128,
    map_feature_dim=64,
    head_num=4,
    dropout=0.3,
    latent_token_num=16,
    beta_schedule="cosine",
    num_workers=0,
    datasets="ETH/UCY",
    test_name=None,
    test_ratio=None,
    split_by_scenario=False,
    cache_dataset=True,
    test_before_train=True,
    test_per_epoch=10,
    save_per_epoch=50,
    reload_checkpoint=None,
    save_path="logs/train/20251009_train_122049_LM2",
)

In [5]:
import numpy as np
import pandas as pd
from tqdm import tqdm

dataset_list = [
    *ETHDataset.load_data_batch(args, "./data/ETH/"),
    *UCYDataset.load_data_batch(args, "./data/UCY/"),
    GCDataset.load_data(args, "./data/GC/Annotation"),
    *SDDDataset.load_data_batch(args, "./data/SDD/"),
]

df_list = []
for dataset in tqdm(dataset_list):
    df_data = dataset.df_data
    map_data = dataset.map_data
    df_data = df_data[df_data['type'] == 'pedestrian']
    traj_length = np.mean([traj[['x', 'y']].diff().pow(2).sum(axis=1).pow(0.5).sum() for id, traj in df_data.groupby('id')])
    traj_duration = np.mean([(traj['f'].max() - traj['f'].min()) / args.fps for id, traj in df_data.groupby('id')])

    row = {
        'dataset': type(dataset).__name__.removesuffix('Dataset'),
        '#Trajectory': df_data['id'].nunique(),
        '#Frame': df_data['f'].nunique(),
        'Time': (df_data['f'].max() - df_data['f'].min()) / args.fps,
        'Area': (map_data.xmax - map_data.xmin) * (map_data.ymax - map_data.ymin),
        'Speed': df_data[['x', 'y']].diff().pow(2).sum(axis=1).pow(0.5).mean() * args.fps,
        'Trajectory-Length': traj_length,
        'Trajectory-Duration': traj_duration,
    }
    df_list.append(row)

df = pd.DataFrame(df_list)

df.groupby('dataset').agg(**{
    '#Scenario': ('#Trajectory', 'count'),
    '#Pedestrian': ('#Trajectory', 'sum'),
    '#Frame': ('#Frame', 'sum'),
    'Time': ('Time', 'sum'),
    'Average Area': ('Area', 'mean'),
    'Average Trajectory-Length': ('Trajectory-Length', 'mean'),
    'Average Trajectory-Duration': ('Trajectory-Duration', 'mean'),
    'Average Speed': ('Speed', 'mean'),
    # 'Area': ('Area', 'sum'),
    # 'Trajectory-Length': ('Trajectory-Length', 'sum'),
    # 'Trajectory-Duration': ('Trajectory-Duration', 'sum'),
    # 'Average Time': ('Time', 'mean'),
})

[None|eth_dataset|I|Oct23 22:00:19|0:07:04.402998] Loading cached dataset-list from data/.cache/ETH.pkl
Loading ETH datasets:   0%|          | 0/2 [00:00<?, ?it/s, seq_eth][None|eth_dataset|I|Oct23 22:00:19|0:07:04.406518] Loading cached dataset from data/.cache/eth_2.5_8_1_1.pkl
Loading ETH datasets:   0%|          | 0/2 [00:00<?, ?it/s, seq_hotel][None|eth_dataset|I|Oct23 22:00:20|0:07:04.426057] Loading cached dataset from data/.cache/hotel_2.5_8_1_1.pkl
Loading ETH datasets: 100%|██████████| 2/2 [00:00<00:00, 51.79it/s, seq_hotel]
[None|ucy_dataset|I|Oct23 22:00:20|0:07:04.445030] Loading cached dataset-list from data/.cache/UCY.pkl
Loading UCY datasets:   0%|          | 0/7 [00:00<?, ?it/s, data_arxiepiskopi/arxiepiskopi1][None|ucy_dataset|I|Oct23 22:00:20|0:07:04.447972] Loading cached dataset from data/.cache/arxiepiskopi-arxiepiskopi1_2.5_8_1_1.pkl
Loading UCY datasets:   0%|          | 0/7 [00:00<?, ?it/s, data_university_students/students001][None|ucy_dataset|I|Oct23 22:00:20|0:07:04.451337] Loading cached dataset from data/.cache/university_students-students001_2.5_8_1_1.pkl
Loading UCY datasets:   0%|          | 0/7 [00:00<?, ?it/s, data_university_students/students003][None|ucy_dataset|I|Oct23 22:00:20|0:07:04.464901] Loading cached dataset from data/.cache/university_students-students003_2.5_8_1_1.pkl
Loading UCY datasets:   0%|          | 0/7 [00:00<?, ?it/s, data_university_students/uni_examples][None|ucy_dataset|I|Oct23 22:00:20|0:07:04.481443] Loading cached dataset from data/.cache/university_students-uni_examples_2.5_8_1_1.pkl
Loading UCY datasets:   0%|          | 0/7 [00:00<?, ?it/s, data_zara/crowds_zara01]              [None|ucy_dataset|I|Oct23 22:00:20|0:07:04.494352] Loading cached dataset from data/.cache/zara-crowds_zara01_2.5_8_1_1.pkl
Loading UCY datasets:   0%|          | 0/7 [00:00<?, ?it/s, data_zara/crowds_zara02][None|ucy_dataset|I|Oct23 22:00:20|0:07:04.510586] Loading cached dataset from data/.cache/zara-crowds_zara02_2.5_8_1_1.pkl
Loading UCY datasets:   0%|          | 0/7 [00:00<?, ?it/s, data_zara/crowds_zara03][None|ucy_dataset|I|Oct23 22:00:20|0:07:04.538526] Loading cached dataset from data/.cache/zara-crowds_zara03_2.5_8_1_1.pkl
Loading UCY datasets: 100%|██████████| 7/7 [00:00<00:00, 66.39it/s, data_zara/crowds_zara03]
[None|gc_dataset|I|Oct23 22:00:20|0:07:04.553883] Loading cached dataset from data/.cache/GC_2.5_8_1_1.pkl
[None|sdd_dataset|I|Oct23 22:00:20|0:07:05.337840] Loading cached dataset-list from data/.cache/SDD.pkl
Loading SDD datasets:   0%|          | 0/60 [00:00<?, ?it/s, bookstore/video0][None|sdd_dataset|I|Oct23 22:00:20|0:07:05.342744] Loading cached dataset from data/.cache/bookstore-0_2.5_8_1_1.pkl
Loading SDD datasets:   0%|          | 0/60 [00:00<?, ?it/s, bookstore/video1][None|sdd_dataset|I|Oct23 22:00:20|0:07:05.400256] Loading cached dataset from data/.cache/bookstore-1_2.5_8_1_1.pkl
Loading SDD datasets:   0%|          | 0/60 [00:00<?, ?it/s, bookstore/video2][None|sdd_dataset|I|Oct23 22:00:21|0:07:05.433975] Loading cached dataset from data/.cache/bookstore-2_2.5_8_1_1.pkl
Loading SDD datasets:   5%|▌         | 3/60 [00:00<00:02, 23.68it/s, bookstore/video3][None|sdd_dataset|I|Oct23 22:00:21|0:07:05.471022] Loading cached dataset from data/.cache/bookstore-3_2.5_8_1_1.pkl
Loading SDD datasets:   5%|▌         | 3/60 [00:00<00:02, 23.68it/s, bookstore/video4][None|sdd_dataset|I|Oct23 22:00:21|0:07:05.537544] Loading cached dataset from data/.cache/bookstore-4_2.5_8_1_1.pkl
Loading SDD datasets:   5%|▌         | 3/60 [00:00<00:02, 23.68it/s, bookstore/video5][None|sdd_dataset|I|Oct23 22:00:21|0:07:05.577541] Loading cached dataset from data/.cache/bookstore-5_2.5_8_1_1.pkl
Loading SDD datasets:  10%|█         | 6/60 [00:00<00:02, 21.58it/s, bookstore/video6][None|sdd_dataset|I|Oct23 22:00:21|0:07:05.618619] Loading cached dataset from data/.cache/bookstore-6_2.5_8_1_1.pkl
Loading SDD datasets:  10%|█         | 6/60 [00:00<00:02, 21.58it/s, coupa/video0]    [None|sdd_dataset|I|Oct23 22:00:21|0:07:05.656139] Loading cached dataset from data/.cache/coupa-0_2.5_8_1_1.pkl
Loading SDD datasets:  10%|█         | 6/60 [00:00<00:02, 21.58it/s, coupa/video1][None|sdd_dataset|I|Oct23 22:00:21|0:07:05.684085] Loading cached dataset from data/.cache/coupa-1_2.5_8_1_1.pkl
Loading SDD datasets:  10%|█         | 6/60 [00:00<00:02, 21.58it/s, coupa/video2][None|sdd_dataset|I|Oct23 22:00:21|0:07:05.709465] Loading cached dataset from data/.cache/coupa-2_2.5_8_1_1.pkl
Loading SDD datasets:  17%|█▋        | 10/60 [00:00<00:01, 26.22it/s, coupa/video3][None|sdd_dataset|I|Oct23 22:00:21|0:07:05.742318] Loading cached dataset from data/.cache/coupa-3_2.5_8_1_1.pkl
Loading SDD datasets:  17%|█▋        | 10/60 [00:00<00:01, 26.22it/s, deathCircle/video0][None|sdd_dataset|I|Oct23 22:00:21|0:07:05.776310] Loading cached dataset from data/.cache/deathCircle-0_2.5_8_1_1.pkl
Loading SDD datasets:  17%|█▋        | 10/60 [00:00<00:01, 26.22it/s, deathCircle/video1][None|sdd_dataset|I|Oct23 22:00:21|0:07:05.851112] Loading cached dataset from data/.cache/deathCircle-1_2.5_8_1_1.pkl
Loading SDD datasets:  22%|██▏       | 13/60 [00:00<00:02, 20.48it/s, deathCircle/video2][None|sdd_dataset|I|Oct23 22:00:21|0:07:05.945693] Loading cached dataset from data/.cache/deathCircle-2_2.5_8_1_1.pkl
Loading SDD datasets:  22%|██▏       | 13/60 [00:00<00:02, 20.48it/s, deathCircle/video3][None|sdd_dataset|I|Oct23 22:00:21|0:07:05.951174] Loading cached dataset from data/.cache/deathCircle-3_2.5_8_1_1.pkl
Loading SDD datasets:  22%|██▏       | 13/60 [00:00<00:02, 20.48it/s, deathCircle/video4][None|sdd_dataset|I|Oct23 22:00:21|0:07:06.033921] Loading cached dataset from data/.cache/deathCircle-4_2.5_8_1_1.pkl
Loading SDD datasets:  22%|██▏       | 13/60 [00:00<00:02, 20.48it/s, gates/video0]      [None|sdd_dataset|I|Oct23 22:00:21|0:07:06.040317] Loading cached dataset from data/.cache/gates-0_2.5_8_1_1.pkl
Loading SDD datasets:  28%|██▊       | 17/60 [00:00<00:01, 23.98it/s, gates/video1][None|sdd_dataset|I|Oct23 22:00:21|0:07:06.069625] Loading cached dataset from data/.cache/gates-1_2.5_8_1_1.pkl
Loading SDD datasets:  28%|██▊       | 17/60 [00:00<00:01, 23.98it/s, gates/video2][None|sdd_dataset|I|Oct23 22:00:21|0:07:06.102436] Loading cached dataset from data/.cache/gates-2_2.5_8_1_1.pkl
Loading SDD datasets:  28%|██▊       | 17/60 [00:00<00:01, 23.98it/s, gates/video3][None|sdd_dataset|I|Oct23 22:00:21|0:07:06.126044] Loading cached dataset from data/.cache/gates-3_2.5_8_1_1.pkl
Loading SDD datasets:  33%|███▎      | 20/60 [00:00<00:01, 25.18it/s, gates/video4][None|sdd_dataset|I|Oct23 22:00:21|0:07:06.175067] Loading cached dataset from data/.cache/gates-4_2.5_8_1_1.pkl
Loading SDD datasets:  33%|███▎      | 20/60 [00:00<00:01, 25.18it/s, gates/video5][None|sdd_dataset|I|Oct23 22:00:21|0:07:06.185624] Loading cached dataset from data/.cache/gates-5_2.5_8_1_1.pkl
Loading SDD datasets:  33%|███▎      | 20/60 [00:00<00:01, 25.18it/s, gates/video6][None|sdd_dataset|I|Oct23 22:00:21|0:07:06.195204] Loading cached dataset from data/.cache/gates-6_2.5_8_1_1.pkl
Loading SDD datasets:  33%|███▎      | 20/60 [00:00<00:01, 25.18it/s, gates/video7][None|sdd_dataset|I|Oct23 22:00:21|0:07:06.202847] Loading cached dataset from data/.cache/gates-7_2.5_8_1_1.pkl
Loading SDD datasets:  33%|███▎      | 20/60 [00:00<00:01, 25.18it/s, gates/video8][None|sdd_dataset|I|Oct23 22:00:21|0:07:06.211351] Loading cached dataset from data/.cache/gates-8_2.5_8_1_1.pkl
Loading SDD datasets:  33%|███▎      | 20/60 [00:00<00:01, 25.18it/s, hyang/video0][None|sdd_dataset|I|Oct23 22:00:21|0:07:06.219755] Loading cached dataset from data/.cache/hyang-0_2.5_8_1_1.pkl
Loading SDD datasets:  33%|███▎      | 20/60 [00:00<00:01, 25.18it/s, hyang/video1][None|sdd_dataset|I|Oct23 22:00:21|0:07:06.260842] Loading cached dataset from data/.cache/hyang-1_2.5_8_1_1.pkl
Loading SDD datasets:  45%|████▌     | 27/60 [00:00<00:00, 35.41it/s, hyang/video10][None|sdd_dataset|I|Oct23 22:00:21|0:07:06.292744] Loading cached dataset from data/.cache/hyang-10_2.5_8_1_1.pkl
Loading SDD datasets:  45%|████▌     | 27/60 [00:00<00:00, 35.41it/s, hyang/video11][None|sdd_dataset|I|Oct23 22:00:21|0:07:06.312391] Loading cached dataset from data/.cache/hyang-11_2.5_8_1_1.pkl
Loading SDD datasets:  45%|████▌     | 27/60 [00:00<00:00, 35.41it/s, hyang/video12][None|sdd_dataset|I|Oct23 22:00:21|0:07:06.332170] Loading cached dataset from data/.cache/hyang-12_2.5_8_1_1.pkl
Loading SDD datasets:  45%|████▌     | 27/60 [00:01<00:00, 35.41it/s, hyang/video13][None|sdd_dataset|I|Oct23 22:00:21|0:07:06.348390] Loading cached dataset from data/.cache/hyang-13_2.5_8_1_1.pkl
Loading SDD datasets:  45%|████▌     | 27/60 [00:01<00:00, 35.41it/s, hyang/video14][None|sdd_dataset|I|Oct23 22:00:21|0:07:06.361191] Loading cached dataset from data/.cache/hyang-14_2.5_8_1_1.pkl
Loading SDD datasets:  45%|████▌     | 27/60 [00:01<00:00, 35.41it/s, hyang/video2] [None|sdd_dataset|I|Oct23 22:00:21|0:07:06.372797] Loading cached dataset from data/.cache/hyang-2_2.5_8_1_1.pkl
Loading SDD datasets:  55%|█████▌    | 33/60 [00:01<00:00, 41.01it/s, hyang/video3][None|sdd_dataset|I|Oct23 22:00:21|0:07:06.401599] Loading cached dataset from data/.cache/hyang-3_2.5_8_1_1.pkl
Loading SDD datasets:  55%|█████▌    | 33/60 [00:01<00:00, 41.01it/s, hyang/video4][None|sdd_dataset|I|Oct23 22:00:22|0:07:06.427702] Loading cached dataset from data/.cache/hyang-4_2.5_8_1_1.pkl
Loading SDD datasets:  55%|█████▌    | 33/60 [00:01<00:00, 41.01it/s, hyang/video5][None|sdd_dataset|I|Oct23 22:00:22|0:07:06.459563] Loading cached dataset from data/.cache/hyang-5_2.5_8_1_1.pkl
Loading SDD datasets:  55%|█████▌    | 33/60 [00:01<00:00, 41.01it/s, hyang/video6][None|sdd_dataset|I|Oct23 22:00:22|0:07:06.480691] Loading cached dataset from data/.cache/hyang-6_2.5_8_1_1.pkl
Loading SDD datasets:  55%|█████▌    | 33/60 [00:01<00:00, 41.01it/s, hyang/video7][None|sdd_dataset|I|Oct23 22:00:22|0:07:06.512632] Loading cached dataset from data/.cache/hyang-7_2.5_8_1_1.pkl
Loading SDD datasets:  63%|██████▎   | 38/60 [00:01<00:00, 41.50it/s, hyang/video8][None|sdd_dataset|I|Oct23 22:00:22|0:07:06.519182] Loading cached dataset from data/.cache/hyang-8_2.5_8_1_1.pkl
Loading SDD datasets:  63%|██████▎   | 38/60 [00:01<00:00, 41.50it/s, hyang/video9][None|sdd_dataset|I|Oct23 22:00:22|0:07:06.523330] Loading cached dataset from data/.cache/hyang-9_2.5_8_1_1.pkl
Loading SDD datasets:  63%|██████▎   | 38/60 [00:01<00:00, 41.50it/s, little/video0][None|sdd_dataset|I|Oct23 22:00:22|0:07:06.527232] Loading cached dataset from data/.cache/little-0_2.5_8_1_1.pkl
Loading SDD datasets:  63%|██████▎   | 38/60 [00:01<00:00, 41.50it/s, little/video1][None|sdd_dataset|I|Oct23 22:00:22|0:07:06.533458] Loading cached dataset from data/.cache/little-1_2.5_8_1_1.pkl
Loading SDD datasets:  63%|██████▎   | 38/60 [00:01<00:00, 41.50it/s, little/video2][None|sdd_dataset|I|Oct23 22:00:22|0:07:06.563012] Loading cached dataset from data/.cache/little-2_2.5_8_1_1.pkl
Loading SDD datasets:  63%|██████▎   | 38/60 [00:01<00:00, 41.50it/s, little/video3][None|sdd_dataset|I|Oct23 22:00:22|0:07:06.588902] Loading cached dataset from data/.cache/little-3_2.5_8_1_1.pkl
Loading SDD datasets:  73%|███████▎  | 44/60 [00:01<00:00, 46.01it/s, nexus/video0] [None|sdd_dataset|I|Oct23 22:00:22|0:07:06.623789] Loading cached dataset from data/.cache/nexus-0_2.5_8_1_1.pkl
Loading SDD datasets:  73%|███████▎  | 44/60 [00:01<00:00, 46.01it/s, nexus/video1][None|sdd_dataset|I|Oct23 22:00:22|0:07:06.650419] Loading cached dataset from data/.cache/nexus-1_2.5_8_1_1.pkl
Loading SDD datasets:  73%|███████▎  | 44/60 [00:01<00:00, 46.01it/s, nexus/video10][None|sdd_dataset|I|Oct23 22:00:22|0:07:06.677037] Loading cached dataset from data/.cache/nexus-10_2.5_8_1_1.pkl
Loading SDD datasets:  73%|███████▎  | 44/60 [00:01<00:00, 46.01it/s, nexus/video11][None|sdd_dataset|I|Oct23 22:00:22|0:07:06.695940] Loading cached dataset from data/.cache/nexus-11_2.5_8_1_1.pkl
Loading SDD datasets:  73%|███████▎  | 44/60 [00:01<00:00, 46.01it/s, nexus/video2] [None|sdd_dataset|I|Oct23 22:00:22|0:07:07.084722] Loading cached dataset from data/.cache/nexus-2_2.5_8_1_1.pkl
Loading SDD datasets:  82%|████████▏ | 49/60 [00:01<00:00, 22.69it/s, nexus/video3][None|sdd_dataset|I|Oct23 22:00:22|0:07:07.112898] Loading cached dataset from data/.cache/nexus-3_2.5_8_1_1.pkl
Loading SDD datasets:  82%|████████▏ | 49/60 [00:01<00:00, 22.69it/s, nexus/video4][None|sdd_dataset|I|Oct23 22:00:22|0:07:07.116935] Loading cached dataset from data/.cache/nexus-4_2.5_8_1_1.pkl
Loading SDD datasets:  82%|████████▏ | 49/60 [00:01<00:00, 22.69it/s, nexus/video5][None|sdd_dataset|I|Oct23 22:00:22|0:07:07.121452] Loading cached dataset from data/.cache/nexus-5_2.5_8_1_1.pkl
Loading SDD datasets:  82%|████████▏ | 49/60 [00:01<00:00, 22.69it/s, nexus/video6][None|sdd_dataset|I|Oct23 22:00:22|0:07:07.128613] Loading cached dataset from data/.cache/nexus-6_2.5_8_1_1.pkl
Loading SDD datasets:  82%|████████▏ | 49/60 [00:01<00:00, 22.69it/s, nexus/video7][None|sdd_dataset|I|Oct23 22:00:22|0:07:07.152395] Loading cached dataset from data/.cache/nexus-7_2.5_8_1_1.pkl
Loading SDD datasets:  82%|████████▏ | 49/60 [00:01<00:00, 22.69it/s, nexus/video8][None|sdd_dataset|I|Oct23 22:00:22|0:07:07.174029] Loading cached dataset from data/.cache/nexus-8_2.5_8_1_1.pkl
Loading SDD datasets:  82%|████████▏ | 49/60 [00:01<00:00, 22.69it/s, nexus/video9][None|sdd_dataset|I|Oct23 22:00:22|0:07:07.203276] Loading cached dataset from data/.cache/nexus-9_2.5_8_1_1.pkl
Loading SDD datasets:  93%|█████████▎| 56/60 [00:01<00:00, 29.71it/s, quad/video0] [None|sdd_dataset|I|Oct23 22:00:22|0:07:07.224025] Loading cached dataset from data/.cache/quad-0_2.5_8_1_1.pkl
Loading SDD datasets:  93%|█████████▎| 56/60 [00:01<00:00, 29.71it/s, quad/video1][None|sdd_dataset|I|Oct23 22:00:22|0:07:07.227080] Loading cached dataset from data/.cache/quad-1_2.5_8_1_1.pkl
Loading SDD datasets:  93%|█████████▎| 56/60 [00:01<00:00, 29.71it/s, quad/video2][None|sdd_dataset|I|Oct23 22:00:22|0:07:07.229930] Loading cached dataset from data/.cache/quad-2_2.5_8_1_1.pkl
Loading SDD datasets:  93%|█████████▎| 56/60 [00:01<00:00, 29.71it/s, quad/video3][None|sdd_dataset|I|Oct23 22:00:22|0:07:07.232659] Loading cached dataset from data/.cache/quad-3_2.5_8_1_1.pkl
Loading SDD datasets: 100%|██████████| 60/60 [00:01<00:00, 31.70it/s, quad/video3]
100%|██████████| 70/70 [00:20<00:00,  3.45it/s]

,#Scenario,#Pedestrian,#Frame,Time,Average Area,Average Trajectory-Length,Average Trajectory-Duration,Average Speed
dataset,,,,,,,,
ETH,2,749,2016,1186.4,490.838498,9.455978,5.785079,2.864477
GC,1,12675,12000,4799.6,3706.106396,33.767133,38.765349,1.587395
SDD,60,13912,42946,17364.0,5673.564034,25.884626,13.928104,3.619905
UCY,7,1480,4460,1801.2,341.527181,14.898826,16.124060,1.722657

In [ ]:
import numpy as np
import pandas as pd
from tqdm import tqdm

args.cache_dataset = False
dataset_list = [
    # *ETHDataset.load_data_batch(args, "./data/ETH/"),
    # *UCYDataset.load_data_batch(args, "./data/UCY/"),
    # GCDataset.load_data(args, "./data/GC/Annotation"),
    # *SDDDataset.load_data_batch(args, "./data/SDD/"),
    *WayMoDataset.load_data_batch(args, "./data/WayMo/Processed"),
]

df_list = []
for dataset in tqdm(dataset_list):
    df_data = dataset.df_data
    map_data = dataset.map_data
    df_data = df_data[df_data['type'] == 'pedestrian']
    traj_length = np.mean([traj[['x', 'y']].diff().pow(2).sum(axis=1).pow(0.5).sum() for id, traj in df_data.groupby('id')])
    traj_duration = np.mean([(traj['f'].max() - traj['f'].min()) / args.fps for id, traj in df_data.groupby('id')])

    row = {
        'dataset': type(dataset).__name__.removesuffix('Dataset'),
        '#Trajectory': df_data['id'].nunique(),
        '#Frame': df_data['f'].nunique(),
        'Time': (df_data['f'].max() - df_data['f'].min()) / args.fps,
        'Area': (map_data.xmax - map_data.xmin) * (map_data.ymax - map_data.ymin),
        'Speed': df_data[['x', 'y']].diff().pow(2).sum(axis=1).pow(0.5).mean() * args.fps,
        'Trajectory-Length': traj_length,
        'Trajectory-Duration': traj_duration,
    }
    df_list.append(row)

df = pd.DataFrame(df_list)

df.groupby('dataset').agg(**{
    '#Scenario': ('#Trajectory', 'count'),
    '#Pedestrian': ('#Trajectory', 'sum'),
    '#Frame': ('#Frame', 'sum'),
    'Time': ('Time', 'sum'),
    'Average Area': ('Area', 'mean'),
    'Average Trajectory-Length': ('Trajectory-Length', 'mean'),
    'Average Trajectory-Duration': ('Trajectory-Duration', 'mean'),
    'Average Speed': ('Speed', 'mean'),
    # 'Area': ('Area', 'sum'),
    # 'Trajectory-Length': ('Trajectory-Length', 'sum'),
    # 'Trajectory-Duration': ('Trajectory-Duration', 'sum'),
    # 'Average Time': ('Time', 'mean'),
})

[None|waymo_dataset|I|Oct09 14:39:58|0:00:22.874223] Caching dataset-list to data/.cache/WayMo-Processed.pkl
Loading SDD datasets:   0%|          | 0/1788 [00:00<?, ?it/s, Processed/00001_2aa43fad083efbf3][None|base_dataset|I|Oct09 14:39:58|0:00:23.361409] Normalized x with mean=125.4211, std=1.0000
[None|base_dataset|I|Oct09 14:39:58|0:00:23.362507] Normalized y with mean=700.9705, std=1.0000
[None|base_dataset|I|Oct09 14:39:58|0:00:23.364026] Normalized map into xmin=-91.1004, xmax=-48.1998, ymin=75.5691, ymax=104.2940
100%|██████████| 30/30 [00:00<00:00, 33.32it/s]
[None|waymo_dataset|I|Oct09 14:39:59|0:00:24.272919] Caching dataset to data/.cache/00001_2aa43fad083efbf3_2.5_8_1_1.pkl
Loading SDD datasets:   0%|          | 1/1788 [00:01<41:32,  1.39s/it, Processed/00004_e2030d66ebfe7b6b][None|base_dataset|I|Oct09 14:39:59|0:00:24.649467] Normalized x with mean=-831.6093, std=1.0000
[None|base_dataset|I|Oct09 14:39:59|0:00:24.651490] Normalized y with mean=-697.3996, std=1.0000
[None|base_dataset|I|Oct09 14:39:59|0:00:24.652725] Normalized map into xmin=-84.5315, xmax=-84.5289, ymin=79.7063, ymax=79.7076
100%|██████████| 30/30 [00:00<00:00, 41.48it/s]
[None|waymo_dataset|I|Oct09 14:40:00|0:00:25.382422] Caching dataset to data/.cache/00004_e2030d66ebfe7b6b_2.5_8_1_1.pkl
Loading SDD datasets:   0%|          | 2/1788 [00:02<36:29,  1.23s/it, Processed/00008_cb3413b9e69ae5ab][None|base_dataset|I|Oct09 14:40:01|0:00:25.844786] Normalized x with mean=1652.6809, std=1.0000
[None|base_dataset|I|Oct09 14:40:01|0:00:25.846376] Normalized y with mean=-5711.8491, std=1.0000
[None|base_dataset|I|Oct09 14:40:01|0:00:25.847429] Normalized map into xmin=-80.3849, xmax=-80.3775, ymin=79.7909, ymax=79.8237
100%|██████████| 30/30 [00:00<00:00, 37.70it/s]
[None|waymo_dataset|I|Oct09 14:40:01|0:00:26.651053] Caching dataset to data/.cache/00008_cb3413b9e69ae5ab_2.5_8_1_1.pkl
Loading SDD datasets:   0%|          | 3/1788 [00:03<37:03,  1.25s/it, Processed/00010_2bc07893b2abbb07][None|base_dataset|I|Oct09 14:40:04|0:00:29.603869] Normalized x with mean=8697.4806, std=1.0000
[None|base_dataset|I|Oct09 14:40:04|0:00:29.607283] Normalized y with mean=10952.1455, std=1.0000
[None|base_dataset|I|Oct09 14:40:04|0:00:29.608239] Normalized map into xmin=-274.0940, xmax=322.9372, ymin=-358.4267, ymax=570.5047
100%|██████████| 30/30 [00:01<00:00, 21.38it/s]
[None|waymo_dataset|I|Oct09 14:40:06|0:00:31.018162] Caching dataset to data/.cache/00010_2bc07893b2abbb07_2.5_8_1_1.pkl
Loading SDD datasets:   0%|          | 4/1788 [00:08<1:15:48,  2.55s/it, Processed/00011_546259711161a341][None|base_dataset|I|Oct09 14:40:41|0:01:06.000425] Normalized x with mean=2287.7559, std=1.0000
[None|base_dataset|I|Oct09 14:40:41|0:01:06.003582] Normalized y with mean=-1672.0944, std=1.0000
[None|base_dataset|I|Oct09 14:40:41|0:01:06.005088] Normalized map into xmin=-573.2956, xmax=714.7725, ymin=-1234.5633, ymax=567.6892
100%|██████████| 30/30 [00:01<00:00, 28.76it/s]
[None|waymo_dataset|I|Oct09 14:40:42|0:01:07.055768] Caching dataset to data/.cache/00011_546259711161a341_2.5_8_1_1.pkl
Loading SDD datasets:   0%|          | 5/1788 [00:44<7:19:28, 14.79s/it, Processed/00012_9859cd1b4315b7de][None|base_dataset|I|Oct09 14:40:43|0:01:08.135496] Normalized x with mean=5156.1220, std=1.0000
[None|base_dataset|I|Oct09 14:40:43|0:01:08.137459] Normalized y with mean=6232.8902, std=1.0000
[None|base_dataset|I|Oct09 14:40:43|0:01:08.138470] Normalized map into xmin=-80.3423, xmax=-80.3066, ymin=75.7761, ymax=75.8638
100%|██████████| 30/30 [00:00<00:00, 40.29it/s]
[None|waymo_dataset|I|Oct09 14:40:44|0:01:08.891119] Caching dataset to data/.cache/00012_9859cd1b4315b7de_2.5_8_1_1.pkl
Loading SDD datasets:   0%|          | 6/1788 [00:46<5:02:01, 10.17s/it, Processed/00017_b29b20e997b76ea3][None|base_dataset|I|Oct09 14:40:44|0:01:09.381467] Normalized x with mean=-5167.3575, std=1.0000
[None|base_dataset|I|Oct09 14:40:44|0:01:09.382707] Normalized y with mean=4817.3124, std=1.0000
[None|base_dataset|I|Oct09 14:40:44|0:01:09.383129] Normalized map into xmin=-86.1114, xmax=-86.0276, ymin=80.7508, ymax=80.9289
100%|██████████| 30/30 [00:00<00:00, 39.37it/s]
[None|waymo_dataset|I|Oct09 14:40:45|0:01:10.150770] Caching dataset to data/.cache/00017_b29b20e997b76ea3_2.5_8_1_1.pkl
Loading SDD datasets:   0%|          | 7/1788 [00:47<3:35:24,  7.26s/it, Processed/00020_5cac897a524d2f40][None|base_dataset|I|Oct09 14:40:45|0:01:10.508746] Normalized x with mean=79.7623, std=1.0000
[None|base_dataset|I|Oct09 14:40:45|0:01:10.510043] Normalized y with mean=-35.5924, std=1.0000
[None|base_dataset|I|Oct09 14:40:45|0:01:10.510483] Normalized map into xmin=-72.8326, xmax=-72.8326, ymin=78.6321, ymax=78.6321
100%|██████████| 30/30 [00:00<00:00, 37.56it/s]
[None|waymo_dataset|I|Oct09 14:40:46|0:01:11.313808] Caching dataset to data/.cache/00020_5cac897a524d2f40_2.5_8_1_1.pkl
Loading SDD datasets:   0%|          | 8/1788 [00:48<2:37:43,  5.32s/it, Processed/00021_104202f4f2590dff][None|base_dataset|I|Oct09 14:40:47|0:01:11.982439] Normalized x with mean=1015.3713, std=1.0000
[None|base_dataset|I|Oct09 14:40:47|0:01:11.984004] Normalized y with mean=-1991.2517, std=1.0000
[None|base_dataset|I|Oct09 14:40:47|0:01:11.984495] Normalized map into xmin=-517.3136, xmax=-124.9990, ymin=-345.9261, ymax=83.9527
100%|██████████| 30/30 [00:00<00:00, 44.78it/s]
[None|waymo_dataset|I|Oct09 14:40:47|0:01:12.658772] Caching dataset to data/.cache/00021_104202f4f2590dff_2.5_8_1_1.pkl
Loading SDD datasets:   1%|          | 9/1788 [00:49<2:01:11,  4.09s/it, Processed/00023_b6152ff56baf6817][None|base_dataset|I|Oct09 14:40:48|0:01:13.029619] Normalized x with mean=2527.6895, std=1.0000
[None|base_dataset|I|Oct09 14:40:48|0:01:13.030514] Normalized y with mean=-1689.4606, std=1.0000
[None|base_dataset|I|Oct09 14:40:48|0:01:13.030828] Normalized map into xmin=-75.7895, xmax=238.6008, ymin=109.2716, ymax=133.7170
100%|██████████| 30/30 [00:00<00:00, 40.41it/s]
[None|waymo_dataset|I|Oct09 14:40:49|0:01:13.776764] Caching dataset to data/.cache/00023_b6152ff56baf6817_2.5_8_1_1.pkl
Loading SDD datasets:   1%|          | 10/1788 [00:50<1:33:36,  3.16s/it, Processed/00027_e12f0928016d6956][None|base_dataset|I|Oct09 14:40:49|0:01:14.103952] Normalized x with mean=1283.5848, std=1.0000
[None|base_dataset|I|Oct09 14:40:49|0:01:14.105241] Normalized y with mean=-1842.9471, std=1.0000
[None|base_dataset|I|Oct09 14:40:49|0:01:14.106074] Normalized map into xmin=-65.9558, xmax=-65.9546, ymin=61.0284, ymax=61.0334
100%|██████████| 30/30 [00:00<00:00, 46.29it/s]
[None|waymo_dataset|I|Oct09 14:40:49|0:01:14.759086] Caching dataset to data/.cache/00027_e12f0928016d6956_2.5_8_1_1.pkl
Loading SDD datasets:   1%|          | 11/1788 [00:51<1:13:48,  2.49s/it, Processed/00028_79776dd1931a3d26][None|base_dataset|I|Oct09 14:40:50|0:01:15.213481] Normalized x with mean=1325.9781, std=1.0000
[None|base_dataset|I|Oct09 14:40:50|0:01:15.214464] Normalized y with mean=-1320.7606, std=1.0000
[None|base_dataset|I|Oct09 14:40:50|0:01:15.215255] Normalized map into xmin=-144.2231, xmax=-144.2210, ymin=106.6086, ymax=106.6131
100%|██████████| 30/30 [00:00<00:00, 32.28it/s]
[None|waymo_dataset|I|Oct09 14:40:51|0:01:16.150561] Caching dataset to data/.cache/00028_79776dd1931a3d26_2.5_8_1_1.pkl
Loading SDD datasets:   1%|          | 12/1788 [00:53<1:03:51,  2.16s/it, Processed/00029_c692808f8d63a7ec][None|base_dataset|I|Oct09 14:40:51|0:01:16.644798] Normalized x with mean=837.6459, std=1.0000
[None|base_dataset|I|Oct09 14:40:51|0:01:16.646378] Normalized y with mean=-1805.9465, std=1.0000
[None|base_dataset|I|Oct09 14:40:51|0:01:16.647260] Normalized map into xmin=-116.2122, xmax=-116.2104, ymin=128.5771, ymax=128.5806
100%|██████████| 30/30 [00:00<00:00, 33.86it/s]
[None|waymo_dataset|I|Oct09 14:40:52|0:01:17.537745] Caching dataset to data/.cache/00029_c692808f8d63a7ec_2.5_8_1_1.pkl
Loading SDD datasets:   1%|          | 13/1788 [00:54<56:55,  1.92s/it, Processed/00031_d8036e6d7e2a86a2]  [None|base_dataset|I|Oct09 14:40:53|0:01:17.877867] Normalized x with mean=-299.3603, std=1.0000
[None|base_dataset|I|Oct09 14:40:53|0:01:17.879081] Normalized y with mean=11859.8207, std=1.0000
[None|base_dataset|I|Oct09 14:40:53|0:01:17.879803] Normalized map into xmin=-73.0968, xmax=-73.0943, ymin=81.0669, ymax=81.0854
100%|██████████| 30/30 [00:00<00:00, 35.57it/s]
[None|waymo_dataset|I|Oct09 14:40:53|0:01:18.729365] Caching dataset to data/.cache/00031_d8036e6d7e2a86a2_2.5_8_1_1.pkl
Loading SDD datasets:   1%|          | 14/1788 [00:55<50:20,  1.70s/it, Processed/00037_3ec9f6dfb2b48d65][None|base_dataset|I|Oct09 14:40:54|0:01:19.414589] Normalized x with mean=3829.5055, std=1.0000
[None|base_dataset|I|Oct09 14:40:54|0:01:19.415653] Normalized y with mean=-3644.1940, std=1.0000
[None|base_dataset|I|Oct09 14:40:54|0:01:19.416258] Normalized map into xmin=-522.0001, xmax=-126.1031, ymin=-414.4445, ymax=88.1881
100%|██████████| 30/30 [00:00<00:00, 42.13it/s]
[None|waymo_dataset|I|Oct09 14:40:55|0:01:20.133593] Caching dataset to data/.cache/00037_3ec9f6dfb2b48d65_2.5_8_1_1.pkl
Loading SDD datasets:   1%|          | 15/1788 [00:57<48:09,  1.63s/it, Processed/00042_9570610abd87b982][None|base_dataset|I|Oct09 14:40:55|0:01:20.592192] Normalized x with mean=-11535.9295, std=1.0000
[None|base_dataset|I|Oct09 14:40:55|0:01:20.593505] Normalized y with mean=-4606.3901, std=1.0000
[None|base_dataset|I|Oct09 14:40:55|0:01:20.594531] Normalized map into xmin=-82.1804, xmax=-82.0673, ymin=71.9010, ymax=72.1178
100%|██████████| 30/30 [00:00<00:00, 40.16it/s]
[None|waymo_dataset|I|Oct09 14:40:56|0:01:21.347018] Caching dataset to data/.cache/00042_9570610abd87b982_2.5_8_1_1.pkl
Loading SDD datasets:   1%|          | 16/1788 [00:58<43:55,  1.49s/it, Processed/00047_90f674b6f7dad649][None|base_dataset|I|Oct09 14:40:57|0:01:21.980801] Normalized x with mean=2337.1275, std=1.0000
[None|base_dataset|I|Oct09 14:40:57|0:01:21.982186] Normalized y with mean=921.5353, std=1.0000
[None|base_dataset|I|Oct09 14:40:57|0:01:21.982926] Normalized map into xmin=-86.3414, xmax=-86.3073, ymin=116.6339, ymax=116.6532
100%|██████████| 30/30 [00:01<00:00, 25.35it/s]
[None|waymo_dataset|I|Oct09 14:40:58|0:01:23.171894] Caching dataset to data/.cache/00047_90f674b6f7dad649_2.5_8_1_1.pkl
Loading SDD datasets:   1%|          | 17/1788 [01:00<46:56,  1.59s/it, Processed/00052_f346701fdc8818d1][None|base_dataset|I|Oct09 14:43:25|0:03:50.168050] Normalized x with mean=11738.1409, std=1.0000
[None|base_dataset|I|Oct09 14:43:25|0:03:50.170981] Normalized y with mean=9499.4972, std=1.0000
[None|base_dataset|I|Oct09 14:43:25|0:03:50.171945] Normalized map into xmin=-115.0058, xmax=6082.3088, ymin=263.1373, ymax=2113.1004
100%|██████████| 30/30 [00:00<00:00, 56.42it/s]
[None|waymo_dataset|I|Oct09 14:43:25|0:03:50.710850] Caching dataset to data/.cache/00052_f346701fdc8818d1_2.5_8_1_1.pkl
Loading SDD datasets:   1%|          | 18/1788 [03:30<22:45:29, 46.29s/it, Processed/00053_568458c3148c034] [None|base_dataset|I|Oct09 14:43:29|0:03:53.883649] Normalized x with mean=9715.7109, std=1.0000
[None|base_dataset|I|Oct09 14:43:29|0:03:53.884535] Normalized y with mean=7939.3898, std=1.0000
[None|base_dataset|I|Oct09 14:43:29|0:03:53.884864] Normalized map into xmin=-80.0459, xmax=-79.8981, ymin=91.3340, ymax=91.4837
100%|██████████| 30/30 [00:00<00:00, 47.77it/s]
[None|waymo_dataset|I|Oct09 14:43:29|0:03:54.516000] Caching dataset to data/.cache/00053_568458c3148c034_2.5_8_1_1.pkl
Loading SDD datasets:   1%|          | 19/1788 [03:31<16:03:41, 32.69s/it, Processed/00061_c93b188ee1c507d5][None|base_dataset|I|Oct09 14:43:30|0:03:55.085439] Normalized x with mean=-5432.4854, std=1.0000
[None|base_dataset|I|Oct09 14:43:30|0:03:55.086748] Normalized y with mean=-11741.9577, std=1.0000
[None|base_dataset|I|Oct09 14:43:30|0:03:55.087507] Normalized map into xmin=-86.9424, xmax=-86.6896, ymin=95.7165, ymax=95.9215
100%|██████████| 30/30 [00:00<00:00, 32.81it/s]
[None|waymo_dataset|I|Oct09 14:43:31|0:03:56.007663] Caching dataset to data/.cache/00061_c93b188ee1c507d5_2.5_8_1_1.pkl
Loading SDD datasets:   1%|          | 20/1788 [03:33<11:27:11, 23.32s/it, Processed/00070_671dec7d5e2fa9fb][None|base_dataset|I|Oct09 14:43:31|0:03:56.599237] Normalized x with mean=-2702.4467, std=1.0000
[None|base_dataset|I|Oct09 14:43:31|0:03:56.600619] Normalized y with mean=12814.1962, std=1.0000
[None|base_dataset|I|Oct09 14:43:31|0:03:56.601386] Normalized map into xmin=-94.5168, xmax=-94.4986, ymin=72.5468, ymax=72.6440
100%|██████████| 30/30 [00:00<00:00, 40.29it/s]
[None|waymo_dataset|I|Oct09 14:43:32|0:03:57.353196] Caching dataset to data/.cache/00070_671dec7d5e2fa9fb_2.5_8_1_1.pkl
Loading SDD datasets:   1%|          | 21/1788 [03:34<8:12:31, 16.72s/it, Processed/00080_9da99cfb12eda13d] [None|base_dataset|I|Oct09 14:43:33|0:03:57.782478] Normalized x with mean=1022.6606, std=1.0000
[None|base_dataset|I|Oct09 14:43:33|0:03:57.783868] Normalized y with mean=-1981.6449, std=1.0000
[None|base_dataset|I|Oct09 14:43:33|0:03:57.784375] Normalized map into xmin=-73.5781, xmax=-73.5751, ymin=79.8388, ymax=79.8429
100%|██████████| 30/30 [00:00<00:00, 37.12it/s]
[None|waymo_dataset|I|Oct09 14:43:33|0:03:58.596845] Caching dataset to data/.cache/00080_9da99cfb12eda13d_2.5_8_1_1.pkl
Loading SDD datasets:   1%|          | 22/1788 [03:35<5:55:29, 12.08s/it, Processed/00086_e372aeb1ab1bdc07][None|base_dataset|I|Oct09 14:43:34|0:03:59.031260] Normalized x with mean=-854.8524, std=1.0000
[None|base_dataset|I|Oct09 14:43:34|0:03:59.032736] Normalized y with mean=1505.3852, std=1.0000
[None|base_dataset|I|Oct09 14:43:34|0:03:59.033793] Normalized map into xmin=-103.4766, xmax=-103.4724, ymin=83.5042, ymax=83.5074
100%|██████████| 30/30 [00:00<00:00, 40.27it/s]
[None|waymo_dataset|I|Oct09 14:43:35|0:03:59.785508] Caching dataset to data/.cache/00086_e372aeb1ab1bdc07_2.5_8_1_1.pkl
Loading SDD datasets:   1%|▏         | 23/1788 [03:36<4:19:10,  8.81s/it, Processed/00088_2e4be3a95170a8c] [None|base_dataset|I|Oct09 14:43:35|0:04:00.198688] Normalized x with mean=2032.7756, std=1.0000
[None|base_dataset|I|Oct09 14:43:35|0:04:00.199698] Normalized y with mean=-2660.7480, std=1.0000
[None|base_dataset|I|Oct09 14:43:35|0:04:00.200193] Normalized map into xmin=-65.6364, xmax=-65.6346, ymin=81.1880, ymax=81.1998
100%|██████████| 30/30 [00:00<00:00, 36.37it/s]
[None|waymo_dataset|I|Oct09 14:43:36|0:04:01.029807] Caching dataset to data/.cache/00088_2e4be3a95170a8c_2.5_8_1_1.pkl
Loading SDD datasets:   1%|▏         | 24/1788 [03:38<3:12:18,  6.54s/it, Processed/00089_ab06ed541440bcf7][None|base_dataset|I|Oct09 14:43:36|0:04:01.363846] Normalized x with mean=501.3230, std=1.0000
[None|base_dataset|I|Oct09 14:43:36|0:04:01.365362] Normalized y with mean=-1166.5623, std=1.0000
[None|base_dataset|I|Oct09 14:43:36|0:04:01.366461] Normalized map into xmin=-101.4570, xmax=-101.4567, ymin=131.7449, ymax=131.7457
100%|██████████| 30/30 [00:00<00:00, 36.85it/s]
[None|waymo_dataset|I|Oct09 14:43:37|0:04:02.186924] Caching dataset to data/.cache/00089_ab06ed541440bcf7_2.5_8_1_1.pkl
Loading SDD datasets:   1%|▏         | 25/1788 [03:39<2:24:42,  4.92s/it, Processed/00094_2cd19fe1c8353aa] [None|base_dataset|I|Oct09 14:43:38|0:04:02.930218] Normalized x with mean=-1003.9373, std=1.0000
[None|base_dataset|I|Oct09 14:43:38|0:04:02.931244] Normalized y with mean=-855.4926, std=1.0000
[None|base_dataset|I|Oct09 14:43:38|0:04:02.931824] Normalized map into xmin=-274.6599, xmax=-15.4412, ymin=-169.0484, ymax=82.4876
100%|██████████| 30/30 [00:00<00:00, 75.99it/s]
[None|waymo_dataset|I|Oct09 14:43:38|0:04:03.331380] Caching dataset to data/.cache/00094_2cd19fe1c8353aa_2.5_8_1_1.pkl
Loading SDD datasets:   1%|▏         | 26/1788 [03:40<1:51:23,  3.79s/it, Processed/00095_8fae861a52e65823][None|base_dataset|I|Oct09 14:43:39|0:04:03.831975] Normalized x with mean=-765.3365, std=1.0000
[None|base_dataset|I|Oct09 14:43:39|0:04:03.833830] Normalized y with mean=-27.2713, std=1.0000
[None|base_dataset|I|Oct09 14:43:39|0:04:03.834691] Normalized map into xmin=-101.0403, xmax=-101.0396, ymin=77.4088, ymax=77.4098
100%|██████████| 30/30 [00:00<00:00, 33.64it/s]
[None|waymo_dataset|I|Oct09 14:43:39|0:04:04.732955] Caching dataset to data/.cache/00095_8fae861a52e65823_2.5_8_1_1.pkl
Loading SDD datasets:   2%|▏         | 27/1788 [03:41<1:30:12,  3.07s/it, Processed/00109_3ed984c47fa60c79][None|base_dataset|I|Oct09 14:43:40|0:04:05.189143] Normalized x with mean=342.2537, std=1.0000
[None|base_dataset|I|Oct09 14:43:40|0:04:05.190746] Normalized y with mean=-2824.8377, std=1.0000
[None|base_dataset|I|Oct09 14:43:40|0:04:05.191527] Normalized map into xmin=-115.7134, xmax=-115.7133, ymin=85.0358, ymax=85.0361
100%|██████████| 30/30 [00:01<00:00, 28.25it/s]
[None|waymo_dataset|I|Oct09 14:43:41|0:04:06.261000] Caching dataset to data/.cache/00109_3ed984c47fa60c79_2.5_8_1_1.pkl
Loading SDD datasets:   2%|▏         | 28/1788 [03:43<1:16:33,  2.61s/it, Processed/00110_e2c96360b78d58a] [None|base_dataset|I|Oct09 14:43:41|0:04:06.623344] Normalized x with mean=1519.2900, std=1.0000
[None|base_dataset|I|Oct09 14:43:41|0:04:06.624769] Normalized y with mean=1497.8922, std=1.0000
[None|base_dataset|I|Oct09 14:43:41|0:04:06.625792] Normalized map into xmin=-67.8654, xmax=-67.8564, ymin=64.3320, ymax=64.3358
100%|██████████| 30/30 [00:00<00:00, 35.81it/s]
[None|waymo_dataset|I|Oct09 14:43:42|0:04:07.471564] Caching dataset to data/.cache/00110_e2c96360b78d58a_2.5_8_1_1.pkl
Loading SDD datasets:   2%|▏         | 29/1788 [03:44<1:04:11,  2.19s/it, Processed/00111_5b8abd9bb491f88e][None|base_dataset|I|Oct09 14:43:43|0:04:07.932152] Normalized x with mean=-5033.8107, std=1.0000
[None|base_dataset|I|Oct09 14:43:43|0:04:07.933758] Normalized y with mean=-13806.1587, std=1.0000
[None|base_dataset|I|Oct09 14:43:43|0:04:07.934582] Normalized map into xmin=-237.3896, xmax=-237.3543, ymin=89.7260, ymax=89.9980
100%|██████████| 30/30 [00:00<00:00, 37.32it/s]
[None|waymo_dataset|I|Oct09 14:43:43|0:04:08.744003] Caching dataset to data/.cache/00111_5b8abd9bb491f88e_2.5_8_1_1.pkl
Loading SDD datasets:   2%|▏         | 30/1788 [03:45<56:06,  1.91s/it, Processed/00119_6f070fa234173dd4]  [None|base_dataset|I|Oct09 14:43:44|0:04:09.204242] Normalized x with mean=-684.4422, std=1.0000
[None|base_dataset|I|Oct09 14:43:44|0:04:09.205295] Normalized y with mean=15033.2270, std=1.0000
[None|base_dataset|I|Oct09 14:43:44|0:04:09.205885] Normalized map into xmin=-92.2288, xmax=-92.2209, ymin=38.6701, ymax=38.6962
100%|██████████| 30/30 [00:01<00:00, 22.06it/s]
[None|waymo_dataset|I|Oct09 14:43:45|0:04:10.569855] Caching dataset to data/.cache/00119_6f070fa234173dd4_2.5_8_1_1.pkl
Loading SDD datasets:   2%|▏         | 31/1788 [03:47<55:17,  1.89s/it, Processed/00121_aa0270a2e8c74ea2][None|base_dataset|I|Oct09 14:43:46|0:04:11.111177] Normalized x with mean=942.1288, std=1.0000
[None|base_dataset|I|Oct09 14:43:46|0:04:11.112580] Normalized y with mean=665.8202, std=1.0000
[None|base_dataset|I|Oct09 14:43:46|0:04:11.113518] Normalized map into xmin=-94.4503, xmax=-94.4481, ymin=87.0977, ymax=87.1018
100%|██████████| 30/30 [00:00<00:00, 30.16it/s]
[None|waymo_dataset|I|Oct09 14:43:47|0:04:12.114476] Caching dataset to data/.cache/00121_aa0270a2e8c74ea2_2.5_8_1_1.pkl
Loading SDD datasets:   2%|▏         | 32/1788 [03:49<52:14,  1.78s/it, Processed/00126_a6c7b46356e7352] [None|base_dataset|I|Oct09 14:43:49|0:04:13.815078] Normalized x with mean=11134.7530, std=1.0000
[None|base_dataset|I|Oct09 14:43:49|0:04:13.817142] Normalized y with mean=9807.1547, std=1.0000
[None|base_dataset|I|Oct09 14:43:49|0:04:13.818258] Normalized map into xmin=-141.7329, xmax=882.5257, ymin=61.5076, ymax=920.6691
100%|██████████| 30/30 [00:00<00:00, 38.72it/s]
[None|waymo_dataset|I|Oct09 14:43:49|0:04:14.597573] Caching dataset to data/.cache/00126_a6c7b46356e7352_2.5_8_1_1.pkl

In [ ]:
import numpy as np
import pandas as pd
from tqdm import tqdm

dataset_list = [
    *ETHDataset.load_data_batch(args, "./data/ETH/"),
    *UCYDataset.load_data_batch(args, "./data/UCY/"),
    GCDataset.load_data(args, "./data/GC/Annotation"),
    *SDDDataset.load_data_batch(args, "./data/SDD/"),
    *WayMoDataset.load_data_batch(args, "./data/WayMo/Processed", total=200),
]

df_list = []
for dataset in tqdm(dataset_list):
    df_data = dataset.df_data
    map_data = dataset.map_data
    traj_length_list = []
    traj_duration_list = []
    traj_speed_list = []
    for id, group in df_data.sort_values(['id', 'f']).groupby('id'):
        if group['type'].nunique() != 1:
            raise ValueError(f"Mixed types in trajectory id {id}")
        if group.iloc[0]['type'] != 'pedestrian':
            continue
        ds = group[['x', 'y']].diff().pow(2).sum(axis=1).pow(0.5)
        dt = group['f'].diff() / args.fps
        traj_length_list.append(ds.sum())
        traj_duration_list.append(dt.sum())
        traj_speed_list.append(ds.sum() / dt.sum() if dt.sum() > 0 else 0.0)
    traj_length = np.mean(traj_length_list)
    traj_duration = np.mean(traj_duration_list)
    traj_speed = np.mean(np.array(traj_speed_list)[np.isfinite(traj_speed_list)])

    row = {
        'dataset': type(dataset).__name__.removesuffix('Dataset'),
        'name': dataset.name,
        '#Pedestrian': df_data[df_data['type'] == 'pedestrian']['id'].nunique(),
        '#Vehicle': df_data[df_data['type'] == 'vehicle']['id'].nunique(),
        '#Frame': df_data['f'].nunique(),
        'Time': (df_data['f'].max() - df_data['f'].min()) / args.fps,
        'Area': (map_data.xmax - map_data.xmin) * (map_data.ymax - map_data.ymin),
        'Average-Speed': traj_speed,
        'Average-Length': traj_length,
        'Average-Duration': traj_duration,
    }
    df_list.append(row)

df = pd.DataFrame(df_list)

df.groupby('dataset').agg(**{
    '#Scenario': ('dataset', 'count'),
    '#Pedestrian': ('#Pedestrian', 'sum'),
    '#Vehicle': ('#Vehicle', 'sum'),
    '#Frame': ('#Frame', 'sum'),
    'Time (s)': ('Time', 'sum'),
    # 'Area (m²)': ('Area', 'sum'),
    'Avg Area (m²)': ('Area', 'mean'),
    'Avg Length (m)': ('Average-Length', 'mean'),
    'Avg Duration (s)': ('Average-Duration', 'mean'),
    'Avg Speed (m/s)': ('Average-Speed', 'mean'),
})

[None|eth_dataset|I|Oct23 22:35:03|0:41:48.232698] Loading cached dataset-list from data/.cache/ETH.pkl
Loading ETH datasets:   0%|          | 0/2 [00:00<?, ?it/s, seq_eth][None|eth_dataset|I|Oct23 22:35:03|0:41:48.236409] Loading cached dataset from data/.cache/eth_2.5_8_1_1.pkl
Loading ETH datasets:   0%|          | 0/2 [00:00<?, ?it/s, seq_hotel][None|eth_dataset|I|Oct23 22:35:03|0:41:48.255839] Loading cached dataset from data/.cache/hotel_2.5_8_1_1.pkl
Loading ETH datasets: 100%|██████████| 2/2 [00:00<00:00, 45.37it/s, seq_hotel]
[None|ucy_dataset|I|Oct23 22:35:03|0:41:48.280620] Loading cached dataset-list from data/.cache/UCY.pkl
Loading UCY datasets:   0%|          | 0/7 [00:00<?, ?it/s, data_arxiepiskopi/arxiepiskopi1][None|ucy_dataset|I|Oct23 22:35:03|0:41:48.284316] Loading cached dataset from data/.cache/arxiepiskopi-arxiepiskopi1_2.5_8_1_1.pkl
Loading UCY datasets:   0%|          | 0/7 [00:00<?, ?it/s, data_university_students/students001][None|ucy_dataset|I|Oct23 22:35:03|0:41:48.291135] Loading cached dataset from data/.cache/university_students-students001_2.5_8_1_1.pkl
Loading UCY datasets:   0%|          | 0/7 [00:00<?, ?it/s, data_university_students/students003][None|ucy_dataset|I|Oct23 22:35:03|0:41:48.307923] Loading cached dataset from data/.cache/university_students-students003_2.5_8_1_1.pkl
Loading UCY datasets:   0%|          | 0/7 [00:00<?, ?it/s, data_university_students/uni_examples][None|ucy_dataset|I|Oct23 22:35:03|0:41:48.323118] Loading cached dataset from data/.cache/university_students-uni_examples_2.5_8_1_1.pkl
Loading UCY datasets:   0%|          | 0/7 [00:00<?, ?it/s, data_zara/crowds_zara01]              [None|ucy_dataset|I|Oct23 22:35:03|0:41:48.336014] Loading cached dataset from data/.cache/zara-crowds_zara01_2.5_8_1_1.pkl
Loading UCY datasets:   0%|          | 0/7 [00:00<?, ?it/s, data_zara/crowds_zara02][None|ucy_dataset|I|Oct23 22:35:03|0:41:48.350796] Loading cached dataset from data/.cache/zara-crowds_zara02_2.5_8_1_1.pkl
Loading UCY datasets:   0%|          | 0/7 [00:00<?, ?it/s, data_zara/crowds_zara03][None|ucy_dataset|I|Oct23 22:35:03|0:41:48.369278] Loading cached dataset from data/.cache/zara-crowds_zara03_2.5_8_1_1.pkl
Loading UCY datasets: 100%|██████████| 7/7 [00:00<00:00, 70.82it/s, data_zara/crowds_zara03]
[None|gc_dataset|I|Oct23 22:35:03|0:41:48.383028] Loading cached dataset from data/.cache/GC_2.5_8_1_1.pkl
[None|sdd_dataset|I|Oct23 22:35:04|0:41:49.033625] Loading cached dataset-list from data/.cache/SDD.pkl
Loading SDD datasets:   0%|          | 0/60 [00:00<?, ?it/s, bookstore/video0][None|sdd_dataset|I|Oct23 22:35:04|0:41:49.037599] Loading cached dataset from data/.cache/bookstore-0_2.5_8_1_1.pkl
Loading SDD datasets:   0%|          | 0/60 [00:00<?, ?it/s, bookstore/video1][None|sdd_dataset|I|Oct23 22:35:04|0:41:49.085699] Loading cached dataset from data/.cache/bookstore-1_2.5_8_1_1.pkl
Loading SDD datasets:   0%|          | 0/60 [00:00<?, ?it/s, bookstore/video2][None|sdd_dataset|I|Oct23 22:35:04|0:41:49.113932] Loading cached dataset from data/.cache/bookstore-2_2.5_8_1_1.pkl
Loading SDD datasets:   5%|▌         | 3/60 [00:00<00:02, 28.42it/s, bookstore/video3][None|sdd_dataset|I|Oct23 22:35:04|0:41:49.144353] Loading cached dataset from data/.cache/bookstore-3_2.5_8_1_1.pkl
Loading SDD datasets:   5%|▌         | 3/60 [00:00<00:02, 28.42it/s, bookstore/video4][None|sdd_dataset|I|Oct23 22:35:04|0:41:49.170917] Loading cached dataset from data/.cache/bookstore-4_2.5_8_1_1.pkl
Loading SDD datasets:   5%|▌         | 3/60 [00:00<00:02, 28.42it/s, bookstore/video5][None|sdd_dataset|I|Oct23 22:35:04|0:41:49.195540] Loading cached dataset from data/.cache/bookstore-5_2.5_8_1_1.pkl
Loading SDD datasets:   5%|▌         | 3/60 [00:00<00:02, 28.42it/s, bookstore/video6][None|sdd_dataset|I|Oct23 22:35:04|0:41:49.225363] Loading cached dataset from data/.cache/bookstore-6_2.5_8_1_1.pkl
Loading SDD datasets:  12%|█▏        | 7/60 [00:00<00:01, 33.79it/s, coupa/video0]    [None|sdd_dataset|I|Oct23 22:35:04|0:41:49.250726] Loading cached dataset from data/.cache/coupa-0_2.5_8_1_1.pkl
Loading SDD datasets:  12%|█▏        | 7/60 [00:00<00:01, 33.79it/s, coupa/video1][None|sdd_dataset|I|Oct23 22:35:04|0:41:49.267976] Loading cached dataset from data/.cache/coupa-1_2.5_8_1_1.pkl
Loading SDD datasets:  12%|█▏        | 7/60 [00:00<00:01, 33.79it/s, coupa/video2][None|sdd_dataset|I|Oct23 22:35:04|0:41:49.336483] Loading cached dataset from data/.cache/coupa-2_2.5_8_1_1.pkl
Loading SDD datasets:  12%|█▏        | 7/60 [00:00<00:01, 33.79it/s, coupa/video3][None|sdd_dataset|I|Oct23 22:35:04|0:41:49.366986] Loading cached dataset from data/.cache/coupa-3_2.5_8_1_1.pkl
Loading SDD datasets:  18%|█▊        | 11/60 [00:00<00:01, 30.34it/s, deathCircle/video0][None|sdd_dataset|I|Oct23 22:35:04|0:41:49.397583] Loading cached dataset from data/.cache/deathCircle-0_2.5_8_1_1.pkl
Loading SDD datasets:  18%|█▊        | 11/60 [00:00<00:01, 30.34it/s, deathCircle/video1][None|sdd_dataset|I|Oct23 22:35:05|0:41:49.445310] Loading cached dataset from data/.cache/deathCircle-1_2.5_8_1_1.pkl
Loading SDD datasets:  18%|█▊        | 11/60 [00:00<00:01, 30.34it/s, deathCircle/video2][None|sdd_dataset|I|Oct23 22:35:05|0:41:49.494450] Loading cached dataset from data/.cache/deathCircle-2_2.5_8_1_1.pkl
Loading SDD datasets:  18%|█▊        | 11/60 [00:00<00:01, 30.34it/s, deathCircle/video3][None|sdd_dataset|I|Oct23 22:35:05|0:41:49.498390] Loading cached dataset from data/.cache/deathCircle-3_2.5_8_1_1.pkl
Loading SDD datasets:  25%|██▌       | 15/60 [00:00<00:01, 28.41it/s, deathCircle/video4][None|sdd_dataset|I|Oct23 22:35:05|0:41:49.550550] Loading cached dataset from data/.cache/deathCircle-4_2.5_8_1_1.pkl
Loading SDD datasets:  25%|██▌       | 15/60 [00:00<00:01, 28.41it/s, gates/video0]      [None|sdd_dataset|I|Oct23 22:35:05|0:41:49.555103] Loading cached dataset from data/.cache/gates-0_2.5_8_1_1.pkl
Loading SDD datasets:  25%|██▌       | 15/60 [00:00<00:01, 28.41it/s, gates/video1][None|sdd_dataset|I|Oct23 22:35:05|0:41:49.576279] Loading cached dataset from data/.cache/gates-1_2.5_8_1_1.pkl
Loading SDD datasets:  25%|██▌       | 15/60 [00:00<00:01, 28.41it/s, gates/video2][None|sdd_dataset|I|Oct23 22:35:05|0:41:49.598152] Loading cached dataset from data/.cache/gates-2_2.5_8_1_1.pkl
Loading SDD datasets:  25%|██▌       | 15/60 [00:00<00:01, 28.41it/s, gates/video3][None|sdd_dataset|I|Oct23 22:35:05|0:41:49.613090] Loading cached dataset from data/.cache/gates-3_2.5_8_1_1.pkl
Loading SDD datasets:  25%|██▌       | 15/60 [00:00<00:01, 28.41it/s, gates/video4][None|sdd_dataset|I|Oct23 22:35:05|0:41:49.639105] Loading cached dataset from data/.cache/gates-4_2.5_8_1_1.pkl
Loading SDD datasets:  25%|██▌       | 15/60 [00:00<00:01, 28.41it/s, gates/video5][None|sdd_dataset|I|Oct23 22:35:05|0:41:49.646222] Loading cached dataset from data/.cache/gates-5_2.5_8_1_1.pkl
Loading SDD datasets:  37%|███▋      | 22/60 [00:00<00:00, 40.27it/s, gates/video6][None|sdd_dataset|I|Oct23 22:35:05|0:41:49.652721] Loading cached dataset from data/.cache/gates-6_2.5_8_1_1.pkl
Loading SDD datasets:  37%|███▋      | 22/60 [00:00<00:00, 40.27it/s, gates/video7][None|sdd_dataset|I|Oct23 22:35:05|0:41:49.666724] Loading cached dataset from data/.cache/gates-7_2.5_8_1_1.pkl
Loading SDD datasets:  37%|███▋      | 22/60 [00:00<00:00, 40.27it/s, gates/video8][None|sdd_dataset|I|Oct23 22:35:05|0:41:49.672545] Loading cached dataset from data/.cache/gates-8_2.5_8_1_1.pkl
Loading SDD datasets:  37%|███▋      | 22/60 [00:00<00:00, 40.27it/s, hyang/video0][None|sdd_dataset|I|Oct23 22:35:05|0:41:49.678585] Loading cached dataset from data/.cache/hyang-0_2.5_8_1_1.pkl
Loading SDD datasets:  37%|███▋      | 22/60 [00:00<00:00, 40.27it/s, hyang/video1][None|sdd_dataset|I|Oct23 22:35:05|0:41:49.712361] Loading cached dataset from data/.cache/hyang-1_2.5_8_1_1.pkl
Loading SDD datasets:  37%|███▋      | 22/60 [00:00<00:00, 40.27it/s, hyang/video10][None|sdd_dataset|I|Oct23 22:35:05|0:41:49.738039] Loading cached dataset from data/.cache/hyang-10_2.5_8_1_1.pkl
Loading SDD datasets:  47%|████▋     | 28/60 [00:00<00:00, 45.11it/s, hyang/video11][None|sdd_dataset|I|Oct23 22:35:05|0:41:49.760146] Loading cached dataset from data/.cache/hyang-11_2.5_8_1_1.pkl
Loading SDD datasets:  47%|████▋     | 28/60 [00:00<00:00, 45.11it/s, hyang/video12][None|sdd_dataset|I|Oct23 22:35:05|0:41:49.778696] Loading cached dataset from data/.cache/hyang-12_2.5_8_1_1.pkl
Loading SDD datasets:  47%|████▋     | 28/60 [00:00<00:00, 45.11it/s, hyang/video13][None|sdd_dataset|I|Oct23 22:35:05|0:41:49.794930] Loading cached dataset from data/.cache/hyang-13_2.5_8_1_1.pkl
Loading SDD datasets:  47%|████▋     | 28/60 [00:00<00:00, 45.11it/s, hyang/video14][None|sdd_dataset|I|Oct23 22:35:05|0:41:49.808908] Loading cached dataset from data/.cache/hyang-14_2.5_8_1_1.pkl
Loading SDD datasets:  47%|████▋     | 28/60 [00:00<00:00, 45.11it/s, hyang/video2] [None|sdd_dataset|I|Oct23 22:35:05|0:41:49.821616] Loading cached dataset from data/.cache/hyang-2_2.5_8_1_1.pkl
Loading SDD datasets:  47%|████▋     | 28/60 [00:00<00:00, 45.11it/s, hyang/video3][None|sdd_dataset|I|Oct23 22:35:05|0:41:49.852683] Loading cached dataset from data/.cache/hyang-3_2.5_8_1_1.pkl
Loading SDD datasets:  57%|█████▋    | 34/60 [00:00<00:00, 45.50it/s, hyang/video4][None|sdd_dataset|I|Oct23 22:35:05|0:41:49.890724] Loading cached dataset from data/.cache/hyang-4_2.5_8_1_1.pkl
Loading SDD datasets:  57%|█████▋    | 34/60 [00:00<00:00, 45.50it/s, hyang/video5][None|sdd_dataset|I|Oct23 22:35:05|0:41:49.925144] Loading cached dataset from data/.cache/hyang-5_2.5_8_1_1.pkl
Loading SDD datasets:  57%|█████▋    | 34/60 [00:00<00:00, 45.50it/s, hyang/video6][None|sdd_dataset|I|Oct23 22:35:05|0:41:49.951711] Loading cached dataset from data/.cache/hyang-6_2.5_8_1_1.pkl
Loading SDD datasets:  57%|█████▋    | 34/60 [00:00<00:00, 45.50it/s, hyang/video7][None|sdd_dataset|I|Oct23 22:35:05|0:41:49.972316] Loading cached dataset from data/.cache/hyang-7_2.5_8_1_1.pkl
Loading SDD datasets:  57%|█████▋    | 34/60 [00:00<00:00, 45.50it/s, hyang/video8][None|sdd_dataset|I|Oct23 22:35:05|0:41:49.975823] Loading cached dataset from data/.cache/hyang-8_2.5_8_1_1.pkl
Loading SDD datasets:  57%|█████▋    | 34/60 [00:00<00:00, 45.50it/s, hyang/video9][None|sdd_dataset|I|Oct23 22:35:05|0:41:49.978929] Loading cached dataset from data/.cache/hyang-9_2.5_8_1_1.pkl
Loading SDD datasets:  57%|█████▋    | 34/60 [00:00<00:00, 45.50it/s, little/video0][None|sdd_dataset|I|Oct23 22:35:05|0:41:49.982169] Loading cached dataset from data/.cache/little-0_2.5_8_1_1.pkl
Loading SDD datasets:  57%|█████▋    | 34/60 [00:00<00:00, 45.50it/s, little/video1][None|sdd_dataset|I|Oct23 22:35:05|0:41:49.987567] Loading cached dataset from data/.cache/little-1_2.5_8_1_1.pkl
Loading SDD datasets:  70%|███████   | 42/60 [00:00<00:00, 50.99it/s, little/video2][None|sdd_dataset|I|Oct23 22:35:05|0:41:50.019068] Loading cached dataset from data/.cache/little-2_2.5_8_1_1.pkl
Loading SDD datasets:  70%|███████   | 42/60 [00:01<00:00, 50.99it/s, little/video3][None|sdd_dataset|I|Oct23 22:35:05|0:41:50.043274] Loading cached dataset from data/.cache/little-3_2.5_8_1_1.pkl
Loading SDD datasets:  70%|███████   | 42/60 [00:01<00:00, 50.99it/s, nexus/video0] [None|sdd_dataset|I|Oct23 22:35:05|0:41:50.080271] Loading cached dataset from data/.cache/nexus-0_2.5_8_1_1.pkl
Loading SDD datasets:  70%|███████   | 42/60 [00:01<00:00, 50.99it/s, nexus/video1][None|sdd_dataset|I|Oct23 22:35:05|0:41:50.105173] Loading cached dataset from data/.cache/nexus-1_2.5_8_1_1.pkl
Loading SDD datasets:  70%|███████   | 42/60 [00:01<00:00, 50.99it/s, nexus/video10][None|sdd_dataset|I|Oct23 22:35:05|0:41:50.138113] Loading cached dataset from data/.cache/nexus-10_2.5_8_1_1.pkl
Loading SDD datasets:  70%|███████   | 42/60 [00:01<00:00, 50.99it/s, nexus/video11][None|sdd_dataset|I|Oct23 22:35:05|0:41:50.173663] Loading cached dataset from data/.cache/nexus-11_2.5_8_1_1.pkl
Loading SDD datasets:  80%|████████  | 48/60 [00:01<00:00, 43.65it/s, nexus/video2] [None|sdd_dataset|I|Oct23 22:35:05|0:41:50.202394] Loading cached dataset from data/.cache/nexus-2_2.5_8_1_1.pkl
Loading SDD datasets:  80%|████████  | 48/60 [00:01<00:00, 43.65it/s, nexus/video3][None|sdd_dataset|I|Oct23 22:35:05|0:41:50.234242] Loading cached dataset from data/.cache/nexus-3_2.5_8_1_1.pkl
Loading SDD datasets:  80%|████████  | 48/60 [00:01<00:00, 43.65it/s, nexus/video4][None|sdd_dataset|I|Oct23 22:35:05|0:41:50.238997] Loading cached dataset from data/.cache/nexus-4_2.5_8_1_1.pkl
Loading SDD datasets:  80%|████████  | 48/60 [00:01<00:00, 43.65it/s, nexus/video5][None|sdd_dataset|I|Oct23 22:35:05|0:41:50.243746] Loading cached dataset from data/.cache/nexus-5_2.5_8_1_1.pkl
Loading SDD datasets:  80%|████████  | 48/60 [00:01<00:00, 43.65it/s, nexus/video6][None|sdd_dataset|I|Oct23 22:35:05|0:41:50.246603] Loading cached dataset from data/.cache/nexus-6_2.5_8_1_1.pkl
Loading SDD datasets:  80%|████████  | 48/60 [00:01<00:00, 43.65it/s, nexus/video7][None|sdd_dataset|I|Oct23 22:35:05|0:41:50.265777] Loading cached dataset from data/.cache/nexus-7_2.5_8_1_1.pkl
Loading SDD datasets:  80%|████████  | 48/60 [00:01<00:00, 43.65it/s, nexus/video8][None|sdd_dataset|I|Oct23 22:35:05|0:41:50.290439] Loading cached dataset from data/.cache/nexus-8_2.5_8_1_1.pkl
Loading SDD datasets:  92%|█████████▏| 55/60 [00:01<00:00, 48.32it/s, nexus/video9][None|sdd_dataset|I|Oct23 22:35:05|0:41:50.316466] Loading cached dataset from data/.cache/nexus-9_2.5_8_1_1.pkl
Loading SDD datasets:  92%|█████████▏| 55/60 [00:01<00:00, 48.32it/s, quad/video0] [None|sdd_dataset|I|Oct23 22:35:05|0:41:50.352489] Loading cached dataset from data/.cache/quad-0_2.5_8_1_1.pkl
Loading SDD datasets:  92%|█████████▏| 55/60 [00:01<00:00, 48.32it/s, quad/video1][None|sdd_dataset|I|Oct23 22:35:05|0:41:50.356299] Loading cached dataset from data/.cache/quad-1_2.5_8_1_1.pkl
Loading SDD datasets:  92%|█████████▏| 55/60 [00:01<00:00, 48.32it/s, quad/video2][None|sdd_dataset|I|Oct23 22:35:05|0:41:50.359296] Loading cached dataset from data/.cache/quad-2_2.5_8_1_1.pkl
Loading SDD datasets:  92%|█████████▏| 55/60 [00:01<00:00, 48.32it/s, quad/video3][None|sdd_dataset|I|Oct23 22:35:05|0:41:50.361664] Loading cached dataset from data/.cache/quad-3_2.5_8_1_1.pkl
Loading SDD datasets: 100%|██████████| 60/60 [00:01<00:00, 45.21it/s, quad/video3]
[None|waymo_dataset|I|Oct23 22:35:05|0:41:50.364490] Loading cached dataset-list from data/.cache/WayMo-Processed.pkl
Loading WayMo datasets:   0%|          | 0/22740 [00:00<?, ?it/s, Processed/00000_10_2bc07893b2abbb07][None|waymo_dataset|I|Oct23 22:35:06|0:41:50.419472] Loading cached dataset from data/.cache/00000_10_2bc07893b2abbb07_2.5_8_1_1.pkl
Loading WayMo datasets:   0%|          | 0/22740 [00:00<?, ?it/s, Processed/00000_11_546259711161a341][None|waymo_dataset|I|Oct23 22:35:06|0:41:50.422541] Loading cached dataset from data/.cache/00000_11_546259711161a341_2.5_8_1_1.pkl
Loading WayMo datasets:   0%|          | 0/22740 [00:00<?, ?it/s, Processed/00000_12_9859cd1b4315b7de][None|waymo_dataset|I|Oct23 22:35:06|0:41:50.426111] Loading cached dataset from data/.cache/00000_12_9859cd1b4315b7de_2.5_8_1_1.pkl
[None|waymo_dataset|E|Oct23 22:35:06|0:41:50.427091] (src/dataset/waymo_dataset.py:132) Failed to load data/WayMo/Processed/00000_12_9859cd1b4315b7de/data.csv.gz: Cached dataset data/.cache/00000_12_9859cd1b4315b7de_2.5_8_1_1.pkl is empty.
Loading WayMo datasets:   0%|          | 0/22740 [00:00<?, ?it/s, Processed/00000_17_b29b20e997b76ea3][None|waymo_dataset|I|Oct23 22:35:06|0:41:50.428210] Loading cached dataset from data/.cache/00000_17_b29b20e997b76ea3_2.5_8_1_1.pkl
Loading WayMo datasets:   0%|          | 0/22740 [00:00<?, ?it/s, Processed/00000_1_2aa43fad083efbf3] [None|waymo_dataset|I|Oct23 22:35:06|0:41:50.430504] Loading cached dataset from data/.cache/00000_1_2aa43fad083efbf3_2.5_8_1_1.pkl
[None|waymo_dataset|E|Oct23 22:35:06|0:41:50.431576] (src/dataset/waymo_dataset.py:132) Failed to load data/WayMo/Processed/00000_1_2aa43fad083efbf3/data.csv.gz: Cached dataset data/.cache/00000_1_2aa43fad083efbf3_2.5_8_1_1.pkl is empty.
Loading WayMo datasets:   0%|          | 0/22740 [00:00<?, ?it/s, Processed/00000_20_5cac897a524d2f40][None|waymo_dataset|I|Oct23 22:35:06|0:41:50.432671] Loading cached dataset from data/.cache/00000_20_5cac897a524d2f40_2.5_8_1_1.pkl
Loading WayMo datasets:   0%|          | 0/22740 [00:00<?, ?it/s, Processed/00000_21_104202f4f2590dff][None|waymo_dataset|I|Oct23 22:35:06|0:41:50.435253] Loading cached dataset from data/.cache/00000_21_104202f4f2590dff_2.5_8_1_1.pkl
Loading WayMo datasets:   0%|          | 0/22740 [00:00<?, ?it/s, Processed/00000_23_b6152ff56baf6817][None|waymo_dataset|I|Oct23 22:35:06|0:41:50.440045] Loading cached dataset from data/.cache/00000_23_b6152ff56baf6817_2.5_8_1_1.pkl
Loading WayMo datasets:   0%|          | 0/22740 [00:00<?, ?it/s, Processed/00000_27_e12f0928016d6956][None|waymo_dataset|I|Oct23 22:35:06|0:41:50.444633] Loading cached dataset from data/.cache/00000_27_e12f0928016d6956_2.5_8_1_1.pkl
Loading WayMo datasets:   0%|          | 0/22740 [00:00<?, ?it/s, Processed/00000_28_79776dd1931a3d26][None|waymo_dataset|I|Oct23 22:35:06|0:41:50.447077] Loading cached dataset from data/.cache/00000_28_79776dd1931a3d26_2.5_8_1_1.pkl
Loading WayMo datasets:   0%|          | 0/22740 [00:00<?, ?it/s, Processed/00000_29_c692808f8d63a7ec][None|waymo_dataset|I|Oct23 22:35:06|0:41:50.449484] Loading cached dataset from data/.cache/00000_29_c692808f8d63a7ec_2.5_8_1_1.pkl
Loading WayMo datasets:   0%|          | 0/22740 [00:00<?, ?it/s, Processed/00000_31_d8036e6d7e2a86a2][None|waymo_dataset|I|Oct23 22:35:06|0:41:50.452970] Loading cached dataset from data/.cache/00000_31_d8036e6d7e2a86a2_2.5_8_1_1.pkl
Loading WayMo datasets:   0%|          | 0/22740 [00:00<?, ?it/s, Processed/00000_37_3ec9f6dfb2b48d65][None|waymo_dataset|I|Oct23 22:35:06|0:41:50.455869] Loading cached dataset from data/.cache/00000_37_3ec9f6dfb2b48d65_2.5_8_1_1.pkl
[None|waymo_dataset|E|Oct23 22:35:06|0:41:50.457376] (src/dataset/waymo_dataset.py:132) Failed to load data/WayMo/Processed/00000_37_3ec9f6dfb2b48d65/data.csv.gz: Cached dataset data/.cache/00000_37_3ec9f6dfb2b48d65_2.5_8_1_1.pkl is empty.
Loading WayMo datasets:   0%|          | 0/22740 [00:00<?, ?it/s, Processed/00000_42_9570610abd87b982][None|waymo_dataset|I|Oct23 22:35:06|0:41:50.459136] Loading cached dataset from data/.cache/00000_42_9570610abd87b982_2.5_8_1_1.pkl
Loading WayMo datasets:   0%|          | 0/22740 [00:00<?, ?it/s, Processed/00000_47_90f674b6f7dad649][None|waymo_dataset|I|Oct23 22:35:06|0:41:50.461014] Loading cached dataset from data/.cache/00000_47_90f674b6f7dad649_2.5_8_1_1.pkl
Loading WayMo datasets:   0%|          | 0/22740 [00:00<?, ?it/s, Processed/00000_4_e2030d66ebfe7b6b] [None|waymo_dataset|I|Oct23 22:35:06|0:41:50.463404] Loading cached dataset from data/.cache/00000_4_e2030d66ebfe7b6b_2.5_8_1_1.pkl
[None|waymo_dataset|E|Oct23 22:35:06|0:41:50.464211] (src/dataset/waymo_dataset.py:132) Failed to load data/WayMo/Processed/00000_4_e2030d66ebfe7b6b/data.csv.gz: Cached dataset data/.cache/00000_4_e2030d66ebfe7b6b_2.5_8_1_1.pkl is empty.
Loading WayMo datasets:   0%|          | 0/22740 [00:00<?, ?it/s, Processed/00000_52_f346701fdc8818d1][None|waymo_dataset|I|Oct23 22:35:06|0:41:50.465046] Loading cached dataset from data/.cache/00000_52_f346701fdc8818d1_2.5_8_1_1.pkl
Loading WayMo datasets:   0%|          | 0/22740 [00:00<?, ?it/s, Processed/00000_53_568458c3148c034] [None|waymo_dataset|I|Oct23 22:35:06|0:41:50.467173] Loading cached dataset from data/.cache/00000_53_568458c3148c034_2.5_8_1_1.pkl

,#Scenario,#Pedestrian,#Vehicle,#Frame,Time,Avg Area (m²),Avg Length (m),Avg Duration (s),Avg Speed (m/s)
dataset,,,,,,,,,
ETH,2,749,0,2016,1186.4,490.838498,9.455978,5.785079,1.761384
GC,1,12675,0,12000,4799.6,3706.106396,33.767133,38.765349,1.245894
SDD,60,13912,5067,43189,17364.4,5673.564034,25.884626,13.928104,2.566208
UCY,7,1480,0,4460,1801.2,341.527181,14.898826,16.124060,1.121061
WayMo,200,2564,1222,9542,3771.6,35854.746073,10.727917,8.800703,1.306734

In [27]:
df_SDD = df[df['dataset'] == 'SDD'].copy()
df_SDD['name-1'] = df_SDD['name'].apply(lambda x: x.split('-')[0])
df_SDD = df_SDD.groupby('name-1').agg(**{
    '#Scenario': ('dataset', 'count'),
    '#Pedestrian': ('#Pedestrian', 'sum'),
    '#Vehicle': ('#Vehicle', 'sum'),
    '#Frame': ('#Frame', 'sum'),
    'Time (s)': ('Time', 'sum'),
    'Avg Area (m²)': ('Area', 'mean'),
    'Avg Length (m)': ('Average-Length', 'mean'),
    'Avg Duration (s)': ('Average-Duration', 'mean'),
    'Avg Speed (m/s)': ('Average-Speed', 'mean'),
})
df_SDD

,#Scenario,#Pedestrian,#Vehicle,#Frame,Time (s),Avg Area (m²),Avg Length (m),Avg Duration (s),Avg Speed (m/s)
name-1,,,,,,,,,
bookstore,7,1857,749,8349,3352.8,2392.926031,22.991514,15.624469,1.866880
coupa,4,480,128,3968,1593.6,1870.831973,23.700563,17.338615,1.745713
deathCircle,5,3921,1913,3344,1335.6,13095.852319,36.938709,10.303382,4.511969
gates,9,1521,738,3911,1560.8,6167.158759,30.642001,13.164299,2.874898
hyang,15,3280,747,10549,4302.4,5735.834415,23.272798,13.995412,2.080584
little,4,857,429,3642,1455.2,3789.044074,32.219972,12.603456,3.481596
nexus,12,1956,355,9258,3698.4,7344.025793,24.549772,15.854989,1.886401
quad,4,40,8,168,65.6,1468.584873,16.073503,9.090000,4.428903